### ISSUE TITLE
Documentation indicates that {{.Os}} and {{.Arch}} can be used in binary field

### ISSUE THREAD

**Issue by jaqx0r** [goreleaser/goreleaser#2021]
In https://goreleaser.com/customization/build/ the documentation indicates that the `binary` field of the `build` list can be templated:

```
The binary name field supports templating. The following build details are exposed:

Key	Description
.Os	GOOS
.Arch	GOARCH
.Arm	GOARM
.Ext	Extension, e.g. .exe
.Target	Build target, e.g. darwin_amd64
```

However in #1151 the issue was raised that these do not work, and the bug was closed as wontfix, suggesting that it is not possible for `.Os` to be templated in this context.

The documentation never gives an example of how to use the `.Os` or `.Arch` template variables in any case, so one fumbles around with attempts like:

```
builds:
  - id: mtail
    main: ./cmd/mtail/main.go
    binary: mtail_{{.Version}}_{{.Os}}_{{.Arch}}
```
in a `.goreleaser.yml` end up with goreleaser reporting errors like
```
  ⨯ release failed after 2.74s error=template: tmpl:1:21: executing "tmpl" at <.Os>: map has no entry for key "Os"
```

Please update the documentation to either:
 * demonstrate correct usage of these template fields with a working example, OR
 * remove the section suggesting that it is possible to template the binary name.

Thanks in advance!

**Comment by caarlos0** [comment]
that feature is only on master... our docs are not versioned, unfortunately..

**Comment by jaqx0r** [comment]
Sorry I don't understand, do you mean templates in 'binary' will be supported after a release is cut?

**Comment by caarlos0** [comment]
releasing v0.155.0, should fix this.

**Comment by jaqx0r** [comment]
Thanks!

**Comment by azr** [comment]
Hello there, when will this version be available in the github-action ? Is there a way for me to use it already ?

**Comment by caarlos0** [comment]
> Hello there, when will this version be available in the github-action ? Is there a way for me to use it already ?

the action uses latest by default, so its available already.

**Comment by azr** [comment]
Hey @caarlos0, thanks for answering, that's weird because I still have the same `executing "tmpl" at <.Os>: map has no entry for key "Os"` issue, ( yes I'm using latest ).

**Comment by caarlos0** [comment]
> Do you have any tip ?

Will need more details... can you open a new issue and follow the instructions in the template? Thx
