### ISSUE TITLE
Goreleaser picks wrong tag if two tags point to same commit

### ISSUE THREAD

**Issue by ecordell** [goreleaser/goreleaser#4134]
### What happened?

I have a release tagged `v1.22.1-rc1` as a prerelease. After testing and confirming it was ready for release, I tagged it as `v1.22.1`. But goreleaser decided that v1.22.1-rc1 was the "latest" tag and built that instead:

```
    • building...                                    commit=666d083225a1f3274112be95a9c6e17cc003be34 latest tag=v1.22.1-rc1
```

Potentially related, there's a clearly incorrect warning that we're running an older version of goreleaser:
```
running goreleaser v1.18.2-pro (outdated, latest is v1.18.1-pro)
```

### How can we reproduce this?

https://github.com/authzed/spicedb/actions/runs/5337620962/jobs/9673898956

### goreleaser version

```bash
v1.18.2-pro
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [X] I am a [sponsor](https://github.com/sponsors/caarlos0/) of [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caarlos0** [comment]
By default git sorts the tags by name, you can change it in the `git` section of the goreleaser config: https://goreleaser.com/customization/git/

---

> running goreleaser v1.18.2-pro (outdated, latest is v1.18.1-pro)

fixed on main, will be released later this month

**Comment by ecordell** [comment]
Thanks! I searched but didn't find this info.

Would it also make sense to have a semver sort option?

**Comment by caarlos0** [comment]
> Would it also make sense to have a semver sort option?

I think it might be a nice addition, not sure how easy to implement though

**Comment by caarlos0** [comment]
v1.21 pro will have `git.tag_sort: semver` :)

**Comment by RangelReale** [comment]
this didn't fix it for me, my Go module has 2 subpackages that have tags added on the same commit, it always pick the wrong one.

```
git tag filter/v0.14.4
git tag value/v0.14.4
git tag v0.14.4
```

```
error=failed to parse tag 'filter/v0.14.3' as semver: Invalid Semantic Version
```

the github action picked the correct tag, can't it be used?

**Comment by caarlos0** [comment]
for that I think you'll need to use the monorepos feature: https://goreleaser.com/customization/monorepo/
